export const ActionTypes = {
    SET_GRIDAPI: 'SET_GRIDAPI',
    SET_COLUMNAPI: 'SET_COLUMNAPI',
    SET_ROWDATA: 'SET_ROWDATA',
    GET_ROWDATA: 'GET_ROWDATA',
    ADD_ROWDATA: 'ADD_ROWDATA',
    DELETE_ROWDATA: 'DELETE_ROWDATA'
}